package com.dazzle.asklepios.web.rest;

import com.dazzle.asklepios.domain.Resource;
import com.dazzle.asklepios.domain.enumeration.ResourceType;
import com.dazzle.asklepios.service.ResourceService;
import com.dazzle.asklepios.web.rest.Helper.PaginationUtil;
import com.dazzle.asklepios.web.rest.Resource.ResourceCreateVM;
import com.dazzle.asklepios.web.rest.Resource.ResourceResponseVM;
import com.dazzle.asklepios.web.rest.Resource.ResourceUpdateVM;
import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;
import java.util.List;

@RestController
@RequestMapping("/api/setup")
public class ResourceController {

    private static final Logger LOG = LoggerFactory.getLogger(ResourceController.class);

    private final ResourceService resourceService;

    public ResourceController(ResourceService resourceService) {
        this.resourceService = resourceService;
    }

    /**
     * {@code POST /resource} : Create a new Resource.
     *
     * <p>Validates the payload, persists the entity, and returns a response model.</p>
     *
     * @param resourceVM the creation payload.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and body of the created resource,
     *         with a {@code Location} header pointing to the new resource;
     *         or {@code 400 (Bad Request)} if the payload is invalid.
     */
    @PostMapping("/resource")
    public ResponseEntity<ResourceResponseVM> createResource(@Valid @RequestBody ResourceCreateVM resourceVM) {
        LOG.debug("REST create Resource payload={}", resourceVM);
        Resource resource = resourceService.create(resourceVM);
        ResourceResponseVM response = ResourceResponseVM.ofEntity(resource);
        LOG.debug("REST create Resource response={}", response);

        return ResponseEntity
                .created(URI.create("/api/setup/resource/" + resource.getId()))
                .body(response);
    }

    /**
     * {@code PUT /resource/{id}} : Update an existing Resource.
     *
     * <p>Updates mutable fields of the resource identified by {@code id}.</p>
     *
     * @param id the identifier of the resource to update.
     * @param resourceUpdateVM the update payload.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the updated resource in the body,
     *         or {@code 404 (Not Found)} if no resource exists with the given {@code id}.
     */
    @PutMapping("/resource/{id}")
    public ResponseEntity<ResourceResponseVM> updateResource(
            @PathVariable Long id,
            @Valid @RequestBody ResourceUpdateVM resourceUpdateVM) {
        LOG.debug("REST update Resource id={} payload={}", id, resourceUpdateVM);
        return resourceService.update(id, resourceUpdateVM)
                .map(r -> ResponseEntity.ok(ResourceResponseVM.ofEntity(r)))
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    /**
     * {@code GET /resource} : Get a paginated list of all Resources.
     *
     * <p>Supports standard Spring pagination parameters: {@code page}, {@code size}, and {@code sort}.</p>
     *
     * <p>Response includes pagination headers generated by {@link PaginationUtil}:
     * {@code X-Total-Count} and {@code Link} for navigation.</p>
     *
     * @param pageable the pagination and sorting information.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)}, a list of resource view models in the body,
     *         and pagination headers.
     */
    @GetMapping("/resource")
    public ResponseEntity<List<ResourceResponseVM>> getAllResources(@ParameterObject Pageable pageable) {
        LOG.debug("REST list Resources page={}", pageable);
        Page<Resource> page = resourceService.findAll(pageable);
        LOG.debug("REST list Resources results={}", page.getContent());
        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(ServletUriComponentsBuilder.fromCurrentRequest(), page);
        return new ResponseEntity<>(page.getContent().stream().map(ResourceResponseVM::ofEntity).toList(), headers, HttpStatus.OK);
    }

    /**
     * {@code GET /resource/by-type/{resourceType}} : Get resources by type (paginated).
     *
     * @param resourceType the resource type to filter by.
     * @param pageable pagination and sorting information.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and a list of resource view models.
     */
    @GetMapping("/resource/by-type/{resourceType}")
    public ResponseEntity<List<ResourceResponseVM>> getByResourceType(
            @PathVariable ResourceType resourceType,
            @ParameterObject Pageable pageable) {

        LOG.debug("REST list Resources by resourceType={} page={}", resourceType, pageable);
        Page<Resource> page = resourceService.findByResourceType(resourceType, pageable);
        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(ServletUriComponentsBuilder.fromCurrentRequest(), page);
        return new ResponseEntity<>(page.getContent().stream().map(ResourceResponseVM::ofEntity).toList(), headers, HttpStatus.OK);
    }

    /**
     * {@code GET /resource/{id}} : Get a single Resource by id.
     *
     * @param id the identifier of the resource to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the resource view model,
     *         or {@code 404 (Not Found)} if the resource does not exist.
     */
    @GetMapping("/resource/{id}")
    public ResponseEntity<ResourceResponseVM> getResource(@PathVariable Long id) {
        LOG.debug("REST get Resource id={}", id);
        return resourceService.findOne(id)
                .map(ResourceResponseVM::ofEntity)
                .map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

    /**
     * {@code PATCH /resource/{id}/toggle-active} : Toggle the {@code isActive} status of a Resource.
     *
     * <p>Flips the active flag for the resource identified by {@code id} and returns the updated resource.</p>
     *
     * @param id the identifier of the resource to toggle.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the updated resource view model,
     *         or {@code 404 (Not Found)} if the resource does not exist.
     */
    @PatchMapping("/resource/{id}/toggle-active")
    public ResponseEntity<ResourceResponseVM> toggleResourceActiveStatus(@PathVariable Long id) {
        LOG.debug("REST toggle Resource isActive id={}", id);
        return resourceService.toggleIsActive(id)
                .map(ResourceResponseVM::ofEntity)
                .map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }
}

