package com.dazzle.asklepios.domain.enumeration.notification;

public enum NotificationCategory {
    APPOINTMENT_CONFIRMATION,
    AUTHENTICATION,
    QUICK_APPOINTMENT,
    APPOINTMENT_RESCHEDULE,
    APPOINTMENT_CANCELLATION,
    MEDICAL_WARNING,
    PAIN_ASSESSMENT,
    HIGH_ALERT_MEDICATION,
    URGENT_ORDER,
    CONSULTATION_CREATED,
    CONSULTATION_REJECTED,
    CONSULTATION_SUBMITTED,
    RESULT_READY
}
