package com.dazzle.asklepios.domain.enumeration.notification;

public enum NotificationCode {
    PATIENT_CREATE_PASSWORD,
    NEW_REFERRAL_REQUEST_ARRIVED,
    PATIENT_MERGE_COMPLETED,

    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    QUICK_APPOINTMENT_CREATED,
    TEMPLATE_INTERVAL_ENDED,
    APPOINTMENT_CONFIRMED,

    MEDICAL_WARNING_SEVERE_CRITICAL,
    PAIN_LEVEL_SEVERE,
    PRESCRIPTION_HIGH_ALERT_MEDICATION_SUBMITTED,
    URGENT_DIAGNOSTIC_ORDER_SUBMITTED,
    CONSULTATION_CREATED,
    CONSULTATION_SUBMITTED,
    CONSULTATION_REJECTED,

    DIAGNOSTIC_LAB_ABNORMAL_RESULT_READY,
    RADIOLOGY_SEVERE_RESULT_READY,
    CRITICAL_LABORATORY_RESULT,
    EMERGENCY_RESUSCITATION_ALERT,
    PRACTITIONER_URGENT_CONSULTATION_CREATED,
    DEPARTMENT_URGENT_CONSULTATION_CREATED,



}
