package com.dazzle.asklepios.domain.enumeration;

public enum BillingConfigurationKey {

    DEFAULT_CURRENCY_ID,
    DEFAULT_PRICE_LIST_ID,
    DEFAULT_CASH_PAYER_ID,
    DEFAULT_PAYMENT_METHOD_ID,
    DEFAULT_TAX_ID,

    DECIMAL_PRECISION,
    ROUNDING_METHOD,

    PRICES_INCLUDE_TAX,
    APPLY_TAX_AUTOMATICALLY,
    ALLOW_TAX_OVERRIDE,
    ALLOW_INVOICE_WITHOUT_PAYER,

    ALLOW_MANUAL_PRICE_OVERRIDE,
    REQUIRE_PRICE_OVERRIDE_REASON,

    ALLOW_NEGATIVE_INVOICE_LINES,

    REQUIRE_ENCOUNTER_REFERENCE,
    REQUIRE_PATIENT_REFERENCE,

    ALLOW_DRAFT_INVOICE,
    AUTO_FINALIZE_INVOICE,

    ALLOW_DISCOUNT,
    ALLOW_MANUAL_DISCOUNT,
    MAXIMUM_MANUAL_DISCOUNT_PERCENTAGE,
    REQUIRE_DISCOUNT_REASON,

    ALLOW_PARTIAL_PAYMENT,
    ALLOW_MULTIPLE_PAYMENT_METHODS,
    ALLOW_OVERPAYMENT,
    ALLOW_PAYMENT_BEFORE_INVOICE_FINALIZATION,
    AUTO_CLOSE_FULLY_PAID_INVOICE,
    ALLOW_UNALLOCATED_PAYMENT,

    ALLOW_INVOICE_CANCELLATION,
    REQUIRE_CANCELLATION_REASON,
    ALLOW_CANCELLATION_AFTER_PAYMENT,

    ALLOW_CREDIT_NOTES,
    REQUIRE_CREDIT_NOTE_REASON,

    ALLOW_REOPEN_FINALIZED_INVOICE,
    REQUIRE_CANCELLATION_APPROVAL,

    INVOICE_PREFIX,
    CREDIT_NOTE_PREFIX,
    RECEIPT_PREFIX,
    PAYMENT_PREFIX,

    INCLUDE_YEAR,
    INCLUDE_FACILITY_CODE,
    SEQUENCE_LENGTH,
    RESET_FREQUENCY,
    NUMBER_SEPARATOR
}