package com.dazzle.asklepios.domain.enumeration;

public enum CdtClass {
    PREVENTIVE_PROCEDURES,
    RESTORATIVE_PROCEDURES,
    ENDODONTIC_PROCEDURES,
    PERIODONTAL_PROCEDURES,
    ORTHODONTIC_PROCEDURES,
    ORAL_AND_MAXILLOFACIAL_SURGERY_PROCEDURES,
    IMPLANT_PROCEDURES,
    UNCLASSIFIED_PROCEDURE,
    DIAGNOSTIC_PROCEDURES,
    PROSTHODONTIC_PROCEDURES
}
