package com.dazzle.asklepios.domain.enumeration;

/**
 * Enum representing medical conditions used in diagnostic test normal ranges.
 */
public enum Condition {
    TYPE_1_DIABETIC,
    TYPE_2_DIABETIC,
    GESTATIONAL_DIABETIC,
    NONE_DIABETIC,

    NORMAL_HYPERTENSION,
    HYPERTENSION_STAGE_1,
    HYPERTENSION_STAGE_2,
    UNCONTROLLED_HYPERTENSION,

    CIRRHOSIS,
    HEPATITIS,
    FATTY_LIVER,

    CHRONIC_KIDNEY_DISEASE,
    DIALYSIS,
    TRANSPLANT,

    EUTHYROID,
    HYPOTHYROID,
    HYPERTHYROID,

    LUPUS,
    RHEUMATOID_ARTHRITIS,

    ACTIVE_CHEMOTHERAPY,
    REMISSION,
    POST_CHEMOTHERAPY,

    IRON_DEFICIENCY,
    HEMOLYTIC,
    APLASTIC,

    ESTROGEN,
    TESTOSTERONE,
    STEROIDS,
    HRT,
    POST_TRANSPLANT,
    CHEMOTHERAPY,
    BIOLOGICS,

    RECENT_BLOOD_TRANSFUSION,
    TRANSFUSION_WITHIN_3_MONTHS,

    HEMODIALYSIS,
    PERITONEAL_DIALYSIS,

    NONE,

    ON_STATINS,
    ON_DIURETICS,
    ON_ANTIDEPRESSANTS,

    SICKLE_CELL,
    THALASSEMIA,
    POLYCYTHEMIA,
    G6PD_DEFICIENCY,
    PKU,
    PHENYLKETONURIA,
    CYSTIC_FIBROSIS
}
