package com.dazzle.asklepios.domain.enumeration;
public enum EncounterAttachmentSource {
    NURSE_STATION_ATTACHMENT,
    PRESCRIPTION_ORDER_ATTACHMENT,
    MEDICATION_ORDER_ATTACHMENT,
    DIAGNOSTIC_ORDER_ATTACHMENT,
    CONSULTATION_ORDER_ATTACHMENT,
    TELE_CONSULTATION_ORDER_ATTACHMENT,
    OPERATION_REQUEST_ATTACHMENT
    ;

}
