package com.dazzle.asklepios.domain.enumeration;

public enum KidneyDiseaseCause {
    DIABETIC_NEPHROPATHY,
    HYPERTENSIVE_NEPHROPATHY,
    GLOMERULONEPHRITIS,
    POLYCYSTIC_KIDNEY_DISEASE,
    CONGENITAL_KIDNEY_DISEASE,
    OBSTRUCTIVE_UROPATHY,
    INTERSTITIAL_NEPHRITIS,
    AUTOIMMUNE_DISEASE,
    UNKNOWN,
    OTHER
}