package com.dazzle.asklepios.domain.enumeration;

public enum ProcedureCategory {
    DIAGNOSTIC_PROCEDURES,
    SURGICAL_PROCEDURES,
    MINIMALLY_INVASIVE_PROCEDURES,
    OBSTETRIC_AND_GYNECOLOGIC_PROCEDURE,
    OT_INTERVENTION_PROCEDURES,
    THERAPEUTIC_PROCEDURES,
    DENTAL_PROCEDURE
}
