package com.dazzle.asklepios.domain.enumeration;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum Screen {
    // Scheduling
    SCHEDULING_SCREEN,

    // Inventory Management
    INVENTORY_TRANSFER,
    INVENTORY_TRANSACTIONS,
    INVENTORY_TRANSFER_APPROVAL,
    PRODUCTS_CATALOG,
    WAREHOUSE_SETUP,
    WAREHOUSE_ITEMS_SETUP,
    DEPARTMENT_STOCK,

    // Billing & Finance
    LEDGER_ACCOUNT,
    PRICE_LISTS,

    // System Setup
    ALLERGENS,
    POTENTIAL_DUPLICATE,
    BRAND_MEDICATIONS,
    LISTS_OF_VALUE,
    MODULES_AND_SCREENS,
    DATA_VALIDATION_MANAGER,
    DVM,

    ACCESS_ROLES,
    FACILITIES,
    DEPARTMENTS,
    UOM_GROUP,
    PRESCRIPTION_INSTRUCTIONS,
    AGE_GROUP,
    PRACTITIONERS,
    ACTIVE_INGREDIENTS,
    METADATA,
    RESOURCES,
    DENTAL_ACTIONS,
    USERS,
    CATALOG_SETUP,
    DIAGNOSTICS_SETUP,
    VACCINE_SETUP,
    PROCEDURE_SETUP,
    ROOM_BED_SETUP,
    MED_MATRIX_SETUP,
    SERVICES_SETUP,
    VACCINE_SCHEDULE_SETUP,
    CHECKLISTS,
    OPERATION_SETUP,
    PURCHASE_APPROVAL,
    QUESTIONNAIRE_SETUP,
    MEDICATION_MATRIX_SETUP,
    MEDICATION_SCHEDULE_SETUP,
    VISIT_DURATION,
    CLINICAL_PROTOCOLS_SETUP,
    SHIFT_SETUP,
    SUPPLIER_SETUP,
    SURGICAL_KITS_SETUP,
    USER,
    TEST_REPORT_TEMPLATE_SETUP,
    PRODUCTS_SETUP,
    LANGUAGE_SETUP,
    DIAGNOSTICS_SETUP_OLD,
    // Front Desk Office
    QUICK_APPOINTMENT,
    PATIENT_REGISTRATION,
    INFORMATION_DESK,
    FILES_MERGE,

    // Emergency
    ER_TRIAGE,

    ER_DEPARTMENT,
    ER_DASHBOARD,

    // Purchasing
    SUPPLIER_MANAGEMENT,
    QUOTATION_MANAGEMENT,
    PAYMENT_TRACKING,
    LIST_OF_REQUISITION,
    PURCHASE_RETURN,
    PURCHASE_REQUISITION,
    REQUISITION_APPROVAL,
    PURCHASE_ORDERS,
    GOODS_RECEIPT_NOTE,

    // Telemedicine
    TELE_CONSULTATIONS_REQUESTS,

    // Inpatient Care
    INPATIENT_LIST,
    WAITING_LIST,


    // Day Case
    DAY_CASE_PATIENT_LIST,

    // Procedures
    PROCEDURE_REQUESTS_LIST,

    // Operation Theater
    OPERATION_REQUESTS,
    RECOVERY_ROOM,
    OPERATION_ROOM_MATERIALS,

    //EMR Module

    ELECTRONIC_MEDICAL_RECORDS,

    // Clinics Management
    PATIENTS_VISITS_LIST,
    REVIEW_RESULTS,


    // Laboratory
    CLINICAL_LABORATORY,

    // Radiology
    IMAGING_RADIOLOGY,

    // Pharmacy
    INTERNAL_DRUG_ORDERS,
    EPRESCRIPTIONS,
    CONTROLLED_MEDICATIONS,

    // Coding Module
    CPT,
    ICD_10,
    LOINC,
    CDT_CODES,
    SNOMED_CT;




    @JsonCreator
    public static Screen fromValue(String value) {
        return Screen.valueOf(value.toUpperCase().replace(" ", "_"));
    }

}
